import nbformat as nbf

nb = nbf.v4.new_notebook()

nb.cells = [
    nbf.v4.new_markdown_cell("# ECO-TRI — Entraînement du modèle\n\nCe notebook couvre 3 compétences :\n- Collecte de données\n- Nettoyage de données\n- Entraînement du modèle"),
    nbf.v4.new_code_cell("import pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import classification_report, accuracy_score\nimport warnings\nwarnings.filterwarnings('ignore')\nprint('Librairies importées !')"),
    nbf.v4.new_markdown_cell("## Collecte de données"),
    nbf.v4.new_code_cell("np.random.seed(42)\ncategories = ['plastique', 'verre', 'papier', 'carton', 'metal', 'organique']\nparams = {\n    'plastique':  dict(poids=(0.05, 0.02), transp=(0.7, 0.2), rigid=(0.4, 0.1), recyclable=0.9),\n    'verre':      dict(poids=(0.35, 0.1),  transp=(0.8, 0.15),rigid=(0.95, 0.05),recyclable=1.0),\n    'papier':     dict(poids=(0.08, 0.03), transp=(0.1, 0.05), rigid=(0.2, 0.1), recyclable=0.85),\n    'carton':     dict(poids=(0.15, 0.05), transp=(0.05, 0.02),rigid=(0.5, 0.15),recyclable=0.9),\n    'metal':      dict(poids=(0.2, 0.08),  transp=(0.0, 0.01), rigid=(0.9, 0.05),recyclable=1.0),\n    'organique':  dict(poids=(0.1, 0.04),  transp=(0.0, 0.01), rigid=(0.1, 0.05),recyclable=0.3),\n}\nrows = []\nfor cat, p in params.items():\n    n_cat = 167\n    rows.append(pd.DataFrame({\n        'categorie':    [cat] * n_cat,\n        'poids_kg':     np.random.normal(p['poids'][0], p['poids'][1], n_cat).clip(0.01),\n        'transparence': np.random.normal(p['transp'][0], p['transp'][1], n_cat).clip(0, 1),\n        'rigidite':     np.random.normal(p['rigid'][0], p['rigid'][1], n_cat).clip(0, 1),\n        'recyclable':   np.random.binomial(1, p['recyclable'], n_cat),\n    }))\ndf = pd.concat(rows, ignore_index=True).sample(frac=1, random_state=42).reset_index(drop=True)\nprint(f'Dataset créé : {len(df)} déchets')\nprint(df['categorie'].value_counts())\ndf.head()"),
    nbf.v4.new_markdown_cell("## Nettoyage des données"),
    nbf.v4.new_code_cell("print('Valeurs manquantes AVANT :')\nprint(df.isnull().sum())\nfor col in ['poids_kg', 'transparence', 'rigidite']:\n    mask = np.random.random(len(df)) < 0.05\n    df.loc[mask, col] = np.nan\nprint('\\nValeurs manquantes ajoutées (5%) :')\nprint(df.isnull().sum())\nfor col in ['poids_kg', 'transparence', 'rigidite']:\n    df[col] = df.groupby('categorie')[col].transform(lambda x: x.fillna(x.median()))\nprint('\\nValeurs manquantes APRÈS nettoyage :')\nprint(df.isnull().sum())\ndf.to_csv('../data/dechets_nettoyes.csv', index=False)\nprint('Dataset nettoyé sauvegardé !')"),
    nbf.v4.new_markdown_cell("## Visualisation des données"),
    nbf.v4.new_code_cell("fig, axes = plt.subplots(1, 2, figsize=(14, 5))\ncolors = ['#22c55e','#3b82f6','#f59e0b','#8b5cf6','#ef4444','#78716c']\ndf['categorie'].value_counts().plot(kind='bar', ax=axes[0], color=colors)\naxes[0].set_title('Répartition des catégories de déchets')\naxes[0].set_xlabel('Catégorie')\naxes[0].set_ylabel('Nombre')\naxes[0].tick_params(axis='x', rotation=30)\ndf.boxplot(column='poids_kg', by='categorie', ax=axes[1])\naxes[1].set_title('Distribution du poids par catégorie')\nplt.suptitle('')\nplt.tight_layout()\nplt.savefig('../docs/viz_donnees.png', dpi=150, bbox_inches='tight')\nplt.show()\nprint('Graphiques sauvegardés !')"),
    nbf.v4.new_markdown_cell("## Entraînement du modèle"),
    nbf.v4.new_code_cell("features = ['poids_kg', 'transparence', 'rigidite', 'recyclable']\nX = df[features]\ny = df['categorie']\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)\nmodel = RandomForestClassifier(n_estimators=100, random_state=42)\nmodel.fit(X_train, y_train)\ny_pred = model.predict(X_test)\naccuracy = accuracy_score(y_test, y_pred)\nprint(f'Précision du modèle : {accuracy * 100:.1f}%')\nprint(classification_report(y_test, y_pred))"),
    nbf.v4.new_markdown_cell("## Sauvegarde du modèle"),
    nbf.v4.new_code_cell("import pickle, os\nos.makedirs('../backend/models', exist_ok=True)\nwith open('../backend/models/model_eco_tri.pkl', 'wb') as f:\n    pickle.dump({'model': model, 'features': features}, f)\nprint(f'Modèle sauvegardé ! Précision : {accuracy * 100:.1f}%')\nprint('Le modèle est prêt !')")
]

nbf.write(nb, 'notebooks/entrainement_modele.ipynb')
print("Notebook créé avec succès !")